// Package cssbox defines the recursive, format-neutral box tree that the CSS
// layout engine consumes. It is the long-lived contract between frontends and
// the engine: box generation (pkg/layout/css) produces it from HTML+CSS today,
// and DOCX lowering converges onto it later. Everything needed for layout is
// resolved onto the box (the computed style and structural intent); the box has
// no back-reference to its source document, so it is independent of any
// frontend. A built tree is read-only and may be shared across the render
// fan-out without locks.
package cssbox

import "github.com/nathanstitt/doctaculous/pkg/css"

// BoxKind is the structural role of a box.
type BoxKind int

const (
	// BoxBlock is a block-level box generated by an element (display:block,
	// list-item, table, flex, grid, ...).
	BoxBlock BoxKind = iota
	// BoxInline is an inline-level box generated by an element (display:inline).
	BoxInline
	// BoxAnonBlock is an anonymous block box wrapping inline-level children of a
	// block container that also has block-level children.
	BoxAnonBlock
	// BoxAnonInline is an anonymous inline box produced when an inline box is
	// split around a block-level descendant (block-in-inline).
	BoxAnonInline
	// BoxAnonTablePart is an anonymous table / row-group / row / cell wrapper
	// inserted by the anonymous-table-box fixup (CSS 17.2.1). Like BoxAnonBlock/
	// BoxAnonInline it carries a zero-value ComputedStyle; its Display/Formatting
	// say which table part it stands in for. isAnonymous() treats it as anonymous.
	BoxAnonTablePart
	// BoxAnonFlexItem is an anonymous block-level flex item wrapping a contiguous
	// run of inline-level content / text inside a flex container (CSS Flexbox 4).
	// Like BoxAnonBlock it carries a zero-value ComputedStyle and establishes a BFC.
	BoxAnonFlexItem
	// BoxAnonGridItem is an anonymous block-level grid item wrapping a contiguous
	// run of inline-level content / text inside a grid container (CSS Grid §6).
	// Like BoxAnonFlexItem it carries a zero-value ComputedStyle and establishes a BFC.
	BoxAnonGridItem
	// BoxReplaced is a replaced element (e.g. <img>): a leaf sized by intrinsics
	// in a later sub-project.
	BoxReplaced
	// BoxText is a run of text: a leaf.
	BoxText
)

// IsBlockLevel reports whether the kind participates in a block formatting
// context as a block-level box.
func (k BoxKind) IsBlockLevel() bool {
	return k == BoxBlock || k == BoxAnonBlock || k == BoxAnonTablePart || k == BoxAnonFlexItem || k == BoxAnonGridItem
}

// IsInlineLevel reports whether the kind participates in an inline formatting
// context as an inline-level box.
func (k BoxKind) IsInlineLevel() bool {
	return k == BoxInline || k == BoxAnonInline || k == BoxText || k == BoxReplaced
}

// DisplayKind is the normalized display of a box, preserved even for layout
// modes not yet implemented (flex/grid/table parts), so later sub-projects add
// their layout algorithm without changing box generation.
type DisplayKind int

const (
	DisplayBlock DisplayKind = iota
	DisplayInline
	DisplayInlineBlock
	DisplayListItem
	DisplayTable
	DisplayTableRowGroup
	DisplayTableHeaderGroup
	DisplayTableFooterGroup
	DisplayTableRow
	DisplayTableColumn
	DisplayTableColumnGroup
	DisplayTableCaption
	DisplayTableCell
	// DisplayFlex is a block-level flex container (display:flex).
	DisplayFlex
	// DisplayInlineFlex is an inline-level flex container (display:inline-flex).
	// Box generation wiring arrives in a later task; the constant is defined here
	// because fixupFlexGrid reads it.
	DisplayInlineFlex
	// DisplayGrid is a block-level grid container (display:grid).
	DisplayGrid
	// DisplayInlineGrid is an inline-level grid container (display:inline-grid).
	// Box generation wiring arrives in a later task; the constant is defined here
	// because fixupFlexGrid reads it.
	DisplayInlineGrid
	// DisplayNone is never emitted as a box (display:none subtrees are pruned);
	// it exists so a DisplayKind can round-trip the value if needed.
	DisplayNone
)

// FormattingContext is the context a box establishes for its children.
type FormattingContext int

const (
	// BlockFC: children are block-level (the default for a block box with
	// block-level children).
	BlockFC FormattingContext = iota
	// InlineFC: children are inline-level (a block box whose children are all
	// inline-level establishes this).
	InlineFC
	// TableFC, FlexFC, GridFC are established by table/flex/grid boxes; their
	// layout arrives in later sub-projects, but the intent is recorded now.
	TableFC
	FlexFC
	GridFC
)

// FloatKind is a box's float value.
type FloatKind int

const (
	FloatNone FloatKind = iota
	FloatLeft
	FloatRight
)

// PositionKind is a box's positioning scheme.
type PositionKind int

const (
	PosStatic PositionKind = iota
	PosRelative
	PosAbsolute
	PosFixed
	// PosRunning is `position: running(name)` (CSS GCPM): the box is removed from normal
	// flow and re-placed into a @page margin box via content: element(name).
	PosRunning
)

// ControlKind identifies a form control rendered as a static replaced widget.
// CtrlNone (the zero value) means the replaced box is not a control (e.g. an
// <img>), so existing replaced content is unaffected.
type ControlKind int

const (
	CtrlNone     ControlKind = iota // not a control
	CtrlText                        // text + text-like input types, and bare <input>
	CtrlPassword                    // <input type=password>
	CtrlCheckbox                    // <input type=checkbox>
	CtrlRadio                       // <input type=radio>
	CtrlButton                      // <button>, <input type=submit|button|reset>
	CtrlTextarea                    // <textarea>
	CtrlSelect                      // <select>
)

// ReplacedContent holds the facts about a replaced element. It carries only the
// source facts (tag + attributes), never a decoded image: decoding is done at
// layout time by the engine (which holds the resource loader and context), so the
// box tree stays pure and read-only. The decoded image and intrinsic size live on
// the layout output (the engine's fragment), not here.
type ReplacedContent struct {
	Tag     string            // e.g. "img"
	Attrs   map[string]string // src, width, height, alt, ...
	Control ControlKind       // form-control kind; CtrlNone for <img>
	Text    string            // control's display text; empty for <img>
}

// Box is a node of the recursive box tree. It is read-only after construction.
type Box struct {
	Kind     BoxKind
	Style    css.ComputedStyle // resolved style; inherited/zero for anonymous boxes
	Children []*Box

	// Text is set only for Kind == BoxText.
	Text string
	// Replaced is set only for Kind == BoxReplaced.
	Replaced *ReplacedContent

	// Layout-intent hints derived from Style at generation time:
	Display    DisplayKind
	Formatting FormattingContext
	Float      FloatKind
	Position   PositionKind
	// RunningName is the running()-element name when Position == PosRunning ("" otherwise).
	RunningName string

	// ColSpan / RowSpan are the HTML colspan/rowspan presentational attributes,
	// read in pkg/html (like <img width/height>), honored only for a
	// DisplayTableCell box; <col span> reuses ColSpan on a DisplayTableColumn box.
	// Zero means "absent" and reads as 1 in the grid builder, so non-table boxes
	// (which never set these) are unaffected.
	ColSpan int
	RowSpan int

	// Marker is the list-item marker (bullet or number) for a DisplayListItem box,
	// resolved at box generation from the box's list-style-type and the CSS counter
	// engine. nil for a non-list-item box or list-style-type:none. It records the
	// resolved marker for inspection/tests; the marker is actually rendered by
	// prepending its text as the item's leading inline child (see resolveCounters).
	Marker *MarkerContent

	// Semantic annotations for the conversion path (markdown / plain-text export).
	// They are ignored by layout and by the raster/PDF backends — those read only
	// Style and the layout-intent hints above — so a tree with these set lays out
	// byte-identically to one without. The frontends populate them at generation
	// time from facts the visual Style cannot preserve: HTML box generation from the
	// source element (pkg/layout/css), DOCX lowering from the paragraph style / rels
	// (pkg/docx/cssbox). A backend that walks the tree for conversion reads them; a
	// backend that only paints never looks.

	// SemTag is the source semantic role, in a small closed vocabulary a Markdown
	// writer can represent: "h1".."h6", "p", "a", "blockquote", "pre", "code",
	// "em", "strong". Empty when the box has no distinguished role (a generic div,
	// an anonymous box). "b"/"i" and DOCX bold/italic are not recorded here — the
	// writer reads Style.Bold/Style.Italic for emphasis — so SemTag is reserved for
	// roles that are otherwise unrecoverable from Style.
	SemTag string
	// HeadingLvl is the heading level 1..6 for a heading box, 0 otherwise. It is
	// redundant with SemTag ("h<n>") but lets a writer branch without parsing the
	// string. For HTML it is the h1..h6 tag; for DOCX it is derived from the
	// paragraph style id (e.g. "Heading2"), clamped to 6.
	HeadingLvl int
	// Href is the resolved hyperlink target for a link box (SemTag == "a"), empty
	// otherwise. The visual tree drops link targets (a link is only blue+underline
	// styling); this carries the URL for the conversion path. HTML reads the href
	// attribute; DOCX resolves the hyperlink relationship id through the document's
	// rels.
	Href string
}

// MarkerContent is a list item's resolved marker. Text is the already-formatted
// marker string including its trailing space (e.g. "• " or "2. ").
//
// Outside records the list-style-position (true = "outside", the default; false =
// "inside"). It is not yet consumed by layout: both positions currently render the
// marker as the item's leading inline text, which — combined with the UA list
// padding-left indent — reads as the default outside (gutter) marker. Honoring
// "inside" (marker inline with no gutter) and a precise outside marker box is a
// layout follow-up; Outside carries the parsed value for when that lands.
type MarkerContent struct {
	Text    string
	Outside bool
}
